/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiAirtableRouteImport } from './routes/api/airtable'
import { Route as AppSimulateurRouteImport } from './routes/_app.simulateur'
import { Route as AppSalariesRouteImport } from './routes/_app.salaries'
import { Route as AppParametresRouteImport } from './routes/_app.parametres'
import { Route as AppDroitsRouteImport } from './routes/_app.droits'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAirtableRoute = ApiAirtableRouteImport.update({
  id: '/api/airtable',
  path: '/api/airtable',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSimulateurRoute = AppSimulateurRouteImport.update({
  id: '/simulateur',
  path: '/simulateur',
  getParentRoute: () => AppRoute,
} as any)
const AppSalariesRoute = AppSalariesRouteImport.update({
  id: '/salaries',
  path: '/salaries',
  getParentRoute: () => AppRoute,
} as any)
const AppParametresRoute = AppParametresRouteImport.update({
  id: '/parametres',
  path: '/parametres',
  getParentRoute: () => AppRoute,
} as any)
const AppDroitsRoute = AppDroitsRouteImport.update({
  id: '/droits',
  path: '/droits',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof AppDashboardRoute
  '/droits': typeof AppDroitsRoute
  '/parametres': typeof AppParametresRoute
  '/salaries': typeof AppSalariesRoute
  '/simulateur': typeof AppSimulateurRoute
  '/api/airtable': typeof ApiAirtableRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof AppDashboardRoute
  '/droits': typeof AppDroitsRoute
  '/parametres': typeof AppParametresRoute
  '/salaries': typeof AppSalariesRoute
  '/simulateur': typeof AppSimulateurRoute
  '/api/airtable': typeof ApiAirtableRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/droits': typeof AppDroitsRoute
  '/_app/parametres': typeof AppParametresRoute
  '/_app/salaries': typeof AppSalariesRoute
  '/_app/simulateur': typeof AppSimulateurRoute
  '/api/airtable': typeof ApiAirtableRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/droits'
    | '/parametres'
    | '/salaries'
    | '/simulateur'
    | '/api/airtable'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/droits'
    | '/parametres'
    | '/salaries'
    | '/simulateur'
    | '/api/airtable'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/dashboard'
    | '/_app/droits'
    | '/_app/parametres'
    | '/_app/salaries'
    | '/_app/simulateur'
    | '/api/airtable'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ApiAirtableRoute: typeof ApiAirtableRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/airtable': {
      id: '/api/airtable'
      path: '/api/airtable'
      fullPath: '/api/airtable'
      preLoaderRoute: typeof ApiAirtableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/simulateur': {
      id: '/_app/simulateur'
      path: '/simulateur'
      fullPath: '/simulateur'
      preLoaderRoute: typeof AppSimulateurRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/salaries': {
      id: '/_app/salaries'
      path: '/salaries'
      fullPath: '/salaries'
      preLoaderRoute: typeof AppSalariesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/parametres': {
      id: '/_app/parametres'
      path: '/parametres'
      fullPath: '/parametres'
      preLoaderRoute: typeof AppParametresRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/droits': {
      id: '/_app/droits'
      path: '/droits'
      fullPath: '/droits'
      preLoaderRoute: typeof AppDroitsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
  AppDroitsRoute: typeof AppDroitsRoute
  AppParametresRoute: typeof AppParametresRoute
  AppSalariesRoute: typeof AppSalariesRoute
  AppSimulateurRoute: typeof AppSimulateurRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppDroitsRoute: AppDroitsRoute,
  AppParametresRoute: AppParametresRoute,
  AppSalariesRoute: AppSalariesRoute,
  AppSimulateurRoute: AppSimulateurRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ApiAirtableRoute: ApiAirtableRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
